name: two_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
    
  dashed_rect : ^0.0.4
  flutter_launcher_icons: ^0.14.3
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  go_router: ^14.7.1
  syncfusion_flutter_calendar: ^29.1.38

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/png/logo.png"
  
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/png/
